language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13

services:
  - docker

install: docker build -t bootclj/boot:latest -f <(curl https://raw.githubusercontent.com/boot-clj/docker-boot/master/boot/3/Dockerfile) .
script: docker run -t bootclj/boot:latest cd ~/.boot/cache/bin/3.0.0-SNAPSHOT/ && ls -a
