language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13

services:
  - docker

before_install:
  - docker build -t boot-clj/openjdk:8-alpine -f ./docker/openjdk.dockerfile .
  - docker build -t boot-clj/clojure:1.10.0 -f ./docker/clojure.dockerfile .
  - docker build -t boot-clj/tools:latest -f ./docker/tools.dockerfile .

install: docker build -t boot-clj/boot:latest -f ./docker/boot2.dockerfile .
script: docker run -t boot-clj/boot:latest cd ~/.boot/cache/bin/3.0.0-SNAPSHOT/ && ls -a
