language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13

install: make deps
script: make test

cache:
  directories:
  - $HOME/.m2
  - $HOME/.boot/cache
  - $HOME/bin
